server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pizzeria_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: kitchen_schema