server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pizzeria_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: order_schema
    jackson:
      serialization:
        write-dates-as-timestamps: false
menu:
  service:
    url: http://localhost:8084/menu
kitchen:
  service:
    url: http://localhost:8086/kitchen/orders
logging:
  level:
    org.springframework.web: DEBUG
    com.pizzeria.order: DEBUG